#ifndef __RISCV_MEMORYMAP_OFFSET_H__
#define __RISCV_MEMORYMAP_OFFSET_H__



// total
#define BW_MMAP_OFFSET_RISCV None
#define RISCV_ADDR_INTERVAL 8
#define BW_UNUSED_RISCV 3
#define NUM_RISCV_SUBMODULE 0

// reg rvisa_opcode
#define BW_RVISA_OPCODE 7

// reg rvisa_regindex
#define BW_RVISA_REGINDEX 5

// reg rvisa_funct3
#define BW_RVISA_FUNCT3 3

// reg rvisa_funct7
#define BW_RVISA_FUNCT7 7

// reg rvisa_shamt
#define BW_RVISA_SHAMT 5

// reg rvisa_type
#define BW_RVISA_TYPE 8
#define RVISA_TYPE_RD 1
#define RVISA_TYPE_RS1 2
#define RVISA_TYPE_RS2 4
#define RVISA_TYPE_FUNCT3 8
#define RVISA_TYPE_FUNCT7 16
#define RVISA_TYPE_IMM 32
#define RVISA_TYPE_B 64
#define RVISA_TYPE_J 128
#define RVISA_TYPE_INDEX_RD 0
#define RVISA_TYPE_INDEX_RS1 1
#define RVISA_TYPE_INDEX_RS2 2
#define RVISA_TYPE_INDEX_FUNCT3 3
#define RVISA_TYPE_INDEX_FUNCT7 4
#define RVISA_TYPE_INDEX_IMM 5
#define RVISA_TYPE_INDEX_B 6
#define RVISA_TYPE_INDEX_J 7
#define RVISA_TYPE_NONE 0

// reg rvisa_property
#define BW_RVISA_PROPERTY 8
#define RVISA_PROPERTY_VARIABLE_CYCLE 1
#define RVISA_PROPERTY_MULTI_CYCLE 2
#define RVISA_PROPERTY_WB 4
#define RVISA_PROPERTY_SIGNED_RS1 8
#define RVISA_PROPERTY_SIGNED_RS2 16
#define RVISA_PROPERTY_LOAD 32
#define RVISA_PROPERTY_STORE 64
#define RVISA_PROPERTY_SECOND_RESULT 128
#define RVISA_PROPERTY_INDEX_VARIABLE_CYCLE 0
#define RVISA_PROPERTY_INDEX_MULTI_CYCLE 1
#define RVISA_PROPERTY_INDEX_WB 2
#define RVISA_PROPERTY_INDEX_SIGNED_RS1 3
#define RVISA_PROPERTY_INDEX_SIGNED_RS2 4
#define RVISA_PROPERTY_INDEX_LOAD 5
#define RVISA_PROPERTY_INDEX_STORE 6
#define RVISA_PROPERTY_INDEX_SECOND_RESULT 7
#define RVISA_PROPERTY_NONE 0

// reg rvisa_opcode32
#define BW_RVISA_OPCODE32 5
#define RVISA_OPCODE32_LOAD 0
#define RVISA_OPCODE32_LOAD_FP 1
#define RVISA_OPCODE32_CUSTOM_0 2
#define RVISA_OPCODE32_MISC_MEM 3
#define RVISA_OPCODE32_OP_IMM 4
#define RVISA_OPCODE32_AUIPC 5
#define RVISA_OPCODE32_OP_IMM_32 6
#define RVISA_OPCODE32_NAN0 7
#define RVISA_OPCODE32_STORE 8
#define RVISA_OPCODE32_STORE_FP 9
#define RVISA_OPCODE32_CUSTOM_1 10
#define RVISA_OPCODE32_AMO 11
#define RVISA_OPCODE32_OP 12
#define RVISA_OPCODE32_LUI 13
#define RVISA_OPCODE32_OP_32 14
#define RVISA_OPCODE32_NAN1 15
#define RVISA_OPCODE32_MADD 16
#define RVISA_OPCODE32_MSUB 17
#define RVISA_OPCODE32_NMSUB 18
#define RVISA_OPCODE32_NMADD 19
#define RVISA_OPCODE32_OP_FP 20
#define RVISA_OPCODE32_NAN3 21
#define RVISA_OPCODE32_NAN4 22
#define RVISA_OPCODE32_NAN5 23
#define RVISA_OPCODE32_BRANCH 24
#define RVISA_OPCODE32_JALR 25
#define RVISA_OPCODE32_NAN6 26
#define RVISA_OPCODE32_JAL 27
#define RVISA_OPCODE32_SYSTEM 28
#define RVISA_OPCODE32_NAN7 29
#define RVISA_OPCODE32_NAN8 30
#define RVISA_OPCODE32_NAN9 31
#define RVISA_OPCODE32_INDEX_LOAD_FP 0
#define RVISA_OPCODE32_INDEX_CUSTOM_0 1
#define RVISA_OPCODE32_INDEX_OP_IMM 2
#define RVISA_OPCODE32_INDEX_STORE 3
#define RVISA_OPCODE32_INDEX_MADD 4

// reg rvisa_bcond
#define BW_RVISA_BCOND 2
#define RVISA_BCOND_EQ 0
#define RVISA_BCOND_NE 1
#define RVISA_BCOND_LT 2
#define RVISA_BCOND_GE 3
#define RVISA_BCOND_INDEX_NE 0
#define RVISA_BCOND_INDEX_LT 1

#endif